apiVersion: v1
kind: Service
metadata:
  name: car-automotive-backend
  labels:
    app: car-automotive-backend
    app.kubernetes.io/name: car-automotive
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: car-automotive-backend

