apiVersion: v1
kind: Service
metadata:
  name: car-automotive-test1-backend
  labels:
    app: car-automotive-test1-backend
    app.kubernetes.io/name: car-automotive-test1
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: car-automotive-test1-backend

