apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: car-automotive
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/akhils0810/Car_automotive.git
    targetRevision: car-automotive
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: car-automotive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

