apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: car-automotive-test1

resources:
  - namespace.yaml
  - ../../base

images:
  - name: 058264492241.dkr.ecr.us-west-2.amazonaws.com/car-automotive-test1-backend
    newTag: latest
  - name: 058264492241.dkr.ecr.us-west-2.amazonaws.com/car-automotive-test1-frontend
    newTag: latest

commonLabels:
  environment: dev

