# ============================================
# Car Automotive Dev Namespace
# ============================================
apiVersion: v1
kind: Namespace
metadata:
  name: car-automotive
  labels:
    app.kubernetes.io/name: car-automotive
    environment: dev

